"""Criação da tabela UserBooks

Revision ID: 5e410ac4b53c
Revises: f2bedbc7879f
Create Date: 2025-03-25 16:46:56.062672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e410ac4b53c'
down_revision = 'f2bedbc7879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_books',
    sa.Column('id_list', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id_book'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_list')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_books')
    # ### end Alembic commands ###
