name: Deploy to GitHub Pages 

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Criar tag com data do deploy (AAAA.MM.DD)
      run: |
        DEPLOY_DATE=$(date +%Y.%m.%d)
        DEPLOY_TIME=$(date +%H%M)
        TAG_NAME="v${DEPLOY_DATE}.${DEPLOY_TIME}"
        git tag -a "$TAG_NAME" -m "Deploy automático da versão ${DEPLOY_DATE}.${DEPLOY_TIME}"
        git push origin "$TAG_NAME"

