name: Linting com ruff
on: push
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: ./lint.py --exit-non-zero-on-fix
